name: CI

on:
  # Pushes to main are disallowed by branch protection rules.
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
    with:
      python-version: '3.9'
    if: ${{ !github.event.pull_request.draft }}

  lint-rust:
    needs: pre-commit
    uses: ./.github/workflows/check-rust.yml
    if: ${{ !github.event.pull_request.draft }}

  python-static-checks:
    needs: pre-commit
    uses: ./.github/workflows/check-python.yml
    strategy:
      matrix:
        python-version: ['3.9', '3.13']
    with:
      python-version: ${{ matrix.python-version }}
    if: ${{ !github.event.pull_request.draft }}

  test-rust:
    needs: [pre-commit, lint-rust]
    uses: ./.github/workflows/test-rust.yml
    if: ${{ !github.event.pull_request.draft }}

  test-python:
    needs: [pre-commit, lint-rust, python-static-checks]
    uses: ./.github/workflows/test-python.yml
    if: ${{ !github.event.pull_request.draft }}

  ci:
    name: CI
    needs: [pre-commit, lint-rust, python-static-checks, test-rust, test-python]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Check all jobs passed
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}
        run: |
          echo "One or more required jobs failed or were cancelled."
          exit 1
      - name: All checks passed
        run: echo "All checks passed successfully!"
