name: Test Python

on:
  # Run on call from other workflows
  workflow_call:
    inputs:
      python-version:
        type: string
        description: 'Python version to use'
        required: false
        default: '3.9'
      os:
        type: string
        description: 'Operating system to use'
        required: false
        default: 'ubuntu-latest'
  # Manual trigger
  workflow_dispatch:

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  test-python:
    name: Run Python Tests
    runs-on: ${{ inputs.os }}
    steps:
      - name: ğŸ” Checkout Code
        uses: actions/checkout@v6

      - name: ğŸ Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}

      - name: âš¡ï¸ Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: ğŸ—ï¸ Build Project
        run: |
          uv pip install --upgrade pip
          uv pip install .[dev]
          pytest --version

      - name: ğŸ§ª Run Tests
        run: |
          pytest -vvv --color=yes --junitxml=junit/test-results-${{ inputs.os }}-${{ inputs.python-version }}.xml

      - name: ğŸ“‚ Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ inputs.os }}-${{ inputs.python-version }}
          path: junit/test-results-${{ inputs.os }}-${{ inputs.python-version }}.xml
        if: ${{ always() }}
